services:
  app:
    build:
      context: .
      dockerfile: QmtdltTools/Dockerfile
    ports:
      - "5083:8080"
      - "8081:8081"
    environment:
      - Redis__ConnectionString=redis:6379
    depends_on:
      - redis
    networks:
      - app-network

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge